trigger:
- refs/heads/*
- refs/pull/*/merge
- refs/tags/*

jobs:
- job: windows_build
  displayName: 'Build for Windows'
  pool:
    vmImage: 'VS2017-Win2016'
  strategy:
    matrix:
      x64:
        TARGET_ARCH: x64
      ia32:
        TARGET_ARCH: ia32
  timeoutInMinutes: 120
  cancelTimeoutInMinutes: 120
  steps:
  - template: azure-pipelines-template.yml
  - script: out\Release\yode.exe test.js
    displayName: Run tests

- job: macos_build
  displayName: 'Build for macOS'
  pool:
    vmImage: 'macOS-10.14'
  strategy:
    matrix:
      x64:
        TARGET_ARCH: x64
  steps:
  - template: azure-pipelines-template.yml
  - script: out/Release/yode test.js
    displayName: Run tests

- job: linux_build
  displayName: 'Build for Linux'
  pool:
    vmImage: 'ubuntu-18.04'
  strategy:
    matrix:
      x64:
        TARGET_ARCH: x64
  steps:
  - script: |
      sudo apt-get update
      sudo apt-get install -y libgtk-3-dev
    displayName: Install dependencies
  - template: azure-pipelines-template.yml
  - script: xvfb-run out/Release/yode test.js
    displayName: Run tests
